export const categories = [
    { name:"Mới" },
    { name:"Âm nhạc" },
    { name:"Thể thao" },
    { name:"Trò chơi" },
    { name:"Hài kịch" },
    { name:"Hoạt họa" },
    { name:"Bóng đá" },
    { name:"Game" },
    { name:"Lập trình" },
    { name:"Mới" },
    { name:"Âm nhạc" },
    { name:"Thể thao" },
    { name:"Trò chơi" },
    { name:"Hài kịch" },
    { name:"Hoạt họa" },
    { name:"Bóng đá" },
    { name:"Game" },
    { name:"Lập trình" },
    { name:"Mới" },
    { name:"Âm nhạc" },
    { name:"Thể thao" },
    { name:"Trò chơi" },
    { name:"Hài kịch" },
    { name:"Hoạt họa" },
    { name:"Bóng đá" },
    { name:"Game" },
    { name:"Lập trình" },
]